import {useEffect,useMemo,useRef,useState} from 'react';
import {Bell,CalendarClock,Check,ChevronRight,Clock3,Copy,HeartPulse,History,Home,LogOut,Menu,Pause,Play,Plus,Settings,ShieldAlert,TimerReset,UserRound,UsersRound,X,Volume2,Wifi} from 'lucide-react';

type Med={id:string;name:string;interval:number;start:string|null;active:boolean};
type Event={id:string;medId:string;scheduled:string;confirmed:string;by:'Paciente'|'Acompanhante'};
type Role='patient'|'companion';
type Tab='home'|'meds'|'history'|'settings';
type DB={patientName:string;shareCode:string;meds:Med[];events:Event[]};
const KEY='controle-med-v1.2-db';
const seed:DB={patientName:'Paciente Demo',shareCode:'DEMO-1234',meds:[
{id:'moxi',name:'Cloridrato de moxifloxacino',interval:540,start:null,active:true},
{id:'pred',name:'Acetato de prednisolona',interval:540,start:null,active:true},
{id:'dorz',name:'Cloridrato de dorzolamida',interval:720,start:null,active:true},
{id:'brim',name:'Tartarato de brimonidina',interval:720,start:null,active:true}
],events:[]};
function load():DB{try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?.meds?x:seed}catch{return seed}}
function isoNow(){return new Date().toISOString()}
function fmt(t:string){return new Date(t).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function mins(ms:number){const m=Math.max(0,Math.floor(Math.abs(ms)/60000));const h=Math.floor(m/60);const r=m%60;return h?`${h}h ${r.toString().padStart(2,'0')}min`:`${r}min`}
function App(){
 const [db,setDb]=useState<DB>(load); const [role,setRole]=useState<Role>(()=>(localStorage.getItem('cm-role') as Role)||'patient'); const [tab,setTab]=useState<Tab>('home'); const [now,setNow]=useState(Date.now()); const [alarm,setAlarm]=useState<Med|null>(null); const [done,setDone]=useState<{med:Med;event:Event}|null>(null); const [menu,setMenu]=useState(false); const audio=useRef<AudioContext|null>(null); const timer=useRef<number|null>(null);
 useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(db));try{const bc=new BroadcastChannel('cm-v12');bc.postMessage(db);bc.close()}catch{}},[db]);
 useEffect(()=>{try{const bc=new BroadcastChannel('cm-v12');bc.onmessage=e=>e.data?.meds&&setDb(e.data);return()=>bc.close()}catch{}},[]);
 const schedule=useMemo(()=>db.meds.filter(m=>m.active&&m.start).map(m=>{const last=[...db.events].filter(e=>e.medId===m.id).sort((a,b)=>+new Date(b.confirmed)-+new Date(a.confirmed))[0];const base=last?.confirmed||m.start!;return {m,due:new Date(+new Date(base)+m.interval*60000)}}).sort((a,b)=>+a.due-+b.due),[db,now]);
 const pending=schedule.filter(x=>+x.due<=now).sort((a,b)=>+a.due-+b.due)[0]; const upcoming=schedule.filter(x=>+x.due>now);
 useEffect(()=>{if(pending&&!alarm&&!done){setAlarm(pending.m);startSound()}},[pending?.m.id,pending?.due]);
 function startSound(){try{const C=window.AudioContext||((window as any).webkitAudioContext);if(!C)return;audio.current=new C();const c=audio.current;const beep=()=>{const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=880;g.gain.value=.16;o.connect(g);g.connect(c.destination);o.start();setTimeout(()=>o.stop(),450)};beep();timer.current=window.setInterval(beep,1200)}catch{}}
 function stopSound(){if(timer.current)clearInterval(timer.current);timer.current=null;audio.current?.close();audio.current=null}
 function save(x:DB){setDb({...x})}
 function confirmMed(m:Med){stopSound();const item=schedule.find(x=>x.m.id===m.id);if(!item)return;const e:Event={id:crypto.randomUUID(),medId:m.id,scheduled:item.due.toISOString(),confirmed:isoNow(),by:role==='patient'?'Paciente':'Acompanhante'};const x={...db,events:[...db.events,e]};save(x);setAlarm(null);setDone({med:m,event:e})}
 function setFirstTime(m:Med){const x={...db,meds:db.meds.map(z=>z.id===m.id?{...z,start:isoNow(),active:true}:z)};save(x)}
 function addMed(){const name=prompt('Nome do medicamento');if(!name?.trim())return;const raw=prompt('Intervalo em minutos (ex.: 720 = 12 horas)','720');const interval=Number(raw);if(!Number.isFinite(interval)||interval<=0)return alert('Informe um intervalo válido.');save({...db,meds:[...db.meds,{id:crypto.randomUUID(),name:name.trim(),interval,start:null,active:true}]})}
 function pause(m:Med){save({...db,meds:db.meds.map(z=>z.id===m.id?{...z,active:!z.active}:z)})}
 function askNotifications(){if('Notification' in window)Notification.requestPermission().then(p=>alert(p==='granted'?'Notificações ativadas.':'Permissão não concedida.'))}
 function copy(){navigator.clipboard?.writeText(db.shareCode);alert('Código copiado.')}
 const next=upcoming[0];
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-20 border-b border-slate-200/70 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-xl items-center justify-between px-5 py-4"><div><div className="text-[10px] font-bold tracking-[.25em] text-slate-400">CONTROLE DE</div><div className="flex items-center gap-2 text-2xl font-semibold"><span className="rounded-2xl bg-blue-50 p-2 text-blue-600"><HeartPulse size={22}/></span>Medicamentos</div><div className="mt-1 flex items-center gap-1 text-sm text-slate-500"><UserRound size={15}/> {role==='patient'?'Paciente':'Acompanhando'}: {db.patientName}</div></div><div className="flex items-center gap-2"><button onClick={askNotifications} className="rounded-xl p-3 text-blue-600 hover:bg-blue-50"><Bell size={21}/></button><button onClick={()=>setMenu(!menu)} className="rounded-xl bg-blue-50 px-4 py-3 font-bold text-blue-600">Sair</button></div></div></header>
 <main className="mx-auto max-w-xl px-5 pt-5 safe-bottom">
 {tab==='home'&&<>
 {alarm&&<section className="alarm-pulse mb-5 overflow-hidden rounded-[28px] bg-red-600 p-6 text-white"><div className="mb-4 flex items-center justify-between"><span className="rounded-full bg-white/15 px-3 py-2 text-xs font-bold uppercase tracking-wide"><ShieldAlert size={15} className="mr-1 inline"/> Dose pendente</span><span className="rounded-full bg-red-800 px-3 py-2 text-xs font-bold">{mins(now-(schedule.find(x=>x.m.id===alarm.id)?.due.getTime()||now))}</span></div><div className="text-sm font-semibold opacity-90">HORA DO MEDICAMENTO</div><h1 className="mt-1 text-3xl font-bold leading-tight">{alarm.name}</h1><div className="mt-5 rounded-2xl bg-red-700/70 p-4"><div className="text-sm opacity-90">Deveria ter sido às</div><div className="text-4xl font-black">{fmt(schedule.find(x=>x.m.id===alarm.id)?.due.toISOString()||isoNow())}</div></div><button onClick={()=>confirmMed(alarm)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-white px-5 py-4 text-lg font-extrabold text-red-700 shadow"><Check size={22}/> CONFIRMAR {role==='patient'?'QUE FOI USADO':'QUE FOI ADMINISTRADO'}</button><div className="mt-3 grid grid-cols-2 gap-3"><button onClick={()=>{stopSound();setAlarm(null)}} className="rounded-2xl border border-white/60 px-4 py-3 font-bold">Adiar 5 min</button><button onClick={()=>{stopSound();setAlarm(null)}} className="rounded-2xl border border-white/60 px-4 py-3 font-bold">Adiar 10 min</button></div></section>}
 {done&&<section className="mb-5 rounded-[28px] bg-emerald-600 p-6 text-white shadow-lg"><div className="flex items-center gap-3"><div className="rounded-full bg-white p-3 text-emerald-600"><Check size={30}/></div><div><div className="text-xl font-black">Medicamento confirmado!</div><div className="text-sm opacity-90">Registrado às {fmt(done.event.confirmed)}</div></div></div><div className="mt-5 rounded-2xl bg-white/15 p-4"><div className="font-bold">{done.med.name}</div><div className="mt-1 text-sm">Próximo horário calculado automaticamente pelo intervalo cadastrado.</div></div><button onClick={()=>setDone(null)} className="mt-4 w-full rounded-2xl bg-white px-4 py-3 font-bold text-emerald-700">CONTINUAR</button></section>}
 {!alarm&&!done&&<section className="mb-6 overflow-hidden rounded-[30px] bg-gradient-to-br from-blue-600 to-blue-700 p-7 text-white shadow-xl shadow-blue-200"><div className="text-sm font-bold uppercase tracking-wider opacity-80">Próximo medicamento</div>{next?<><div className="mt-2 text-2xl font-semibold">{next.m.name}</div><div className="mt-2 text-6xl font-black tracking-tight">{fmt(next.due.toISOString())}</div><div className="mt-2 text-lg font-bold">Em {mins(next.due.getTime()-now)}</div><div className="mt-2 text-sm opacity-80">Você será alertado quando chegar a hora.</div></>:<div className="mt-3 text-lg font-medium">Defina o primeiro horário de cada medicamento.</div>}</section>}
 <div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 text-xl font-bold"><CalendarClock size={22}/> Próximos horários</h2></div>
 <div className="space-y-3">{upcoming.slice(0,6).map(x=><div key={x.m.id} className="flex items-center gap-4 rounded-3xl border-l-4 border-blue-600 bg-white p-4 shadow-sm"><div className="rounded-2xl bg-blue-50 p-3 text-blue-600"><Clock3 size={23}/></div><div className="min-w-0 flex-1"><div className="truncate font-bold">{x.m.name}</div><div className="text-sm text-slate-500">{fmt(x.due.toISOString())} · Em {mins(x.due.getTime()-now)}</div></div><ChevronRight className="text-slate-400" size={20}/></div>)}{!upcoming.length&&!pending&&<div className="rounded-3xl border border-dashed border-slate-300 bg-white p-7 text-center text-slate-500">Nenhum próximo horário. Cadastre ou defina o primeiro horário.</div>}</div>
 <section className="mt-5 rounded-3xl border border-blue-100 bg-blue-50/70 p-5"><div className="flex items-center gap-3"><UsersRound className="text-blue-600"/><div><div className="font-bold">Acompanhamento familiar</div><div className="text-sm text-slate-500">Código para acompanhar este paciente</div></div></div><div className="mt-3 flex items-center justify-between rounded-2xl bg-white p-3"><strong className="text-xl tracking-widest text-blue-600">{db.shareCode}</strong><button onClick={copy} className="rounded-xl bg-blue-50 p-3 text-blue-600"><Copy size={19}/></button></div></section>
 </>}
 {tab==='meds'&&<><div className="mb-5 flex items-center justify-between"><div><h2 className="text-2xl font-bold">Medicamentos</h2><p className="text-sm text-slate-500">Configure uma vez. O próximo horário depende da confirmação real.</p></div><button onClick={addMed} className="rounded-2xl bg-blue-600 p-3 text-white shadow"><Plus/></button></div><div className="space-y-3">{db.meds.map(m=><div key={m.id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{m.name}</h3><p className="mt-1 text-sm text-slate-500">Intervalo: {m.interval>=1440?`${(m.interval/1440).toFixed(1)} dias`:m.interval>=60?`${(m.interval/60).toFixed(1)} horas`:`${m.interval} minutos`}</p></div><button onClick={()=>pause(m)} className={`rounded-xl p-2 ${m.active?'bg-emerald-50 text-emerald-600':'bg-amber-50 text-amber-600'}`}>{m.active?<Pause size={18}/>:<Play size={18}/>}</button></div>{!m.start?<button onClick={()=>setFirstTime(m)} className="mt-4 w-full rounded-2xl bg-blue-600 px-4 py-3 font-bold text-white">Definir horário — já tomei agora</button>:<div className="mt-4 flex items-center justify-between rounded-2xl bg-slate-50 p-3 text-sm"><span>Base: {fmt(m.start)}</span><span className="font-semibold text-emerald-600">Ativo</span></div>}</div>)}</div></>}
 {tab==='history'&&<><h2 className="mb-5 text-2xl font-bold">Histórico</h2><div className="space-y-3">{[...db.events].reverse().map(e=><div key={e.id} className="rounded-3xl bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-2xl bg-emerald-50 p-3 text-emerald-600"><Check size={20}/></div><div className="flex-1"><div className="font-bold">{db.meds.find(m=>m.id===e.medId)?.name||'Medicamento'}</div><div className="text-sm text-slate-500">Previsto {fmt(e.scheduled)} · Confirmado {fmt(e.confirmed)}</div><div className="text-xs font-semibold text-slate-400">{e.by}</div></div></div></div>)}{!db.events.length&&<div className="rounded-3xl bg-white p-8 text-center text-slate-500">Nenhuma dose confirmada ainda.</div>}</div></>}
 {tab==='settings'&&<><h2 className="mb-5 text-2xl font-bold">Configurações</h2><div className="space-y-3"><button onClick={askNotifications} className="flex w-full items-center gap-3 rounded-3xl bg-white p-5 text-left shadow-sm"><Bell className="text-blue-600"/><div><b>Notificações</b><p className="text-sm text-slate-500">Solicitar permissão do navegador</p></div></button><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='controle-medicamentos-v1.2-backup.json';a.click()}} className="flex w-full items-center gap-3 rounded-3xl bg-white p-5 text-left shadow-sm"><Wifi className="text-blue-600"/><div><b>Exportar backup</b><p className="text-sm text-slate-500">Salvar seus dados em JSON</p></div></button><div className="rounded-3xl bg-amber-50 p-5 text-sm text-amber-900"><b>Importante:</b> este app organiza horários e registros; não altera prescrição nem substitui orientação profissional. Um navegador também não consegue garantir alarme sonoro exato quando o sistema encerra a página.</div></div></>}
 </main><nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-slate-200 bg-white/95 px-2 pb-[env(safe-area-inset-bottom)] backdrop-blur"><div className="mx-auto grid max-w-xl grid-cols-4 py-2"><Nav active={tab==='home'} onClick={()=>setTab('home')} icon={<Home/>} label="Início"/><Nav active={tab==='meds'} onClick={()=>setTab('meds')} icon={<TimerReset/>} label="Medicamentos"/><Nav active={tab==='history'} onClick={()=>setTab('history')} icon={<History/>} label="Histórico"/><Nav active={tab==='settings'} onClick={()=>setTab('settings')} icon={<Settings/>} label="Configurações"/></div></nav>{menu&&<div className="fixed inset-0 z-40 bg-black/20" onClick={()=>setMenu(false)}><div className="absolute right-4 top-20 w-64 rounded-3xl bg-white p-4 shadow-2xl" onClick={e=>e.stopPropagation()}><button onClick={()=>{setRole('patient');localStorage.setItem('cm-role','patient');setMenu(false)}} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><UserRound/> Usar como paciente</button><button onClick={()=>{setRole('companion');localStorage.setItem('cm-role','companion');setMenu(false)}} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><UsersRound/> Acompanhar familiar</button><button onClick={()=>{localStorage.removeItem(KEY);location.reload()}} className="mt-2 flex w-full items-center gap-3 rounded-2xl p-3 text-left text-red-600 hover:bg-red-50"><LogOut/> Restaurar demonstração</button></div></div>}</div>}
function Nav({active,onClick,icon,label}:{active:boolean;onClick:()=>void;icon:JSX.Element;label:string}){return <button onClick={onClick} className={`flex flex-col items-center gap-1 rounded-2xl px-2 py-2 text-xs font-semibold ${active?'bg-blue-50 text-blue-600':'text-slate-500'}`}>{icon}{label}</button>}
export default App;