import {useEffect,useMemo,useRef,useState} from 'react';
import {Bell,CalendarDays,Check,ChevronRight,Clock3,Copy,HeartPulse,History,Home,LogOut,Pause,Play,Plus,Settings,ShieldAlert,UserRound,UsersRound,X,Volume2} from 'lucide-react';

type Med={id:string;name:string;interval:number;start:string|null;active:boolean;form?:string;dose?:string};
type Event={id:string;medId:string;scheduled:string;confirmed:string;by:'Paciente'|'Acompanhante'};
type Role='patient'|'companion'; type Tab='home'|'meds'|'history'|'settings';
type DB={patientName:string;shareCode:string;meds:Med[];events:Event[]};
const KEY='controle-med-v1.2-db';
const seed:DB={patientName:'Paciente Demo',shareCode:'DEMO-1234',meds:[
{id:'moxi',name:'Cloridrato de moxifloxacino',interval:540,start:null,active:true,form:'Colírio',dose:'1 gota'},
{id:'pred',name:'Acetato de prednisolona',interval:540,start:null,active:true,form:'Colírio',dose:'1 gota'},
{id:'dorz',name:'Cloridrato de dorzolamida',interval:720,start:null,active:true,form:'Colírio',dose:'1 gota'},
{id:'brim',name:'Tartarato de brimonidina',interval:720,start:null,active:true,form:'Colírio',dose:'1 gota'}],events:[]};
function load():DB{try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?.meds?x:seed}catch{return seed}}
const nowIso=()=>new Date().toISOString();
const fmt=(t:string)=>new Date(t).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
const dateFmt=(t:string)=>new Date(t).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});
function duration(ms:number){const m=Math.max(0,Math.floor(Math.abs(ms)/60000));const h=Math.floor(m/60),r=m%60;return h?`${h}h ${r.toString().padStart(2,'0')}min`:`${r}min`}
function App(){
 const [db,setDb]=useState<DB>(load); const [role,setRole]=useState<Role>(()=>(localStorage.getItem('cm-role') as Role)||'patient'); const [tab,setTab]=useState<Tab>('home'); const [now,setNow]=useState(Date.now()); const [alarm,setAlarm]=useState<Med|null>(null); const [done,setDone]=useState<{med:Med;event:Event;next:string}|null>(null); const [menu,setMenu]=useState(false); const [showAdd,setShowAdd]=useState(false); const [snoozes,setSnoozes]=useState<Record<string,number>>({}); const audio=useRef<AudioContext|null>(null); const timer=useRef<number|null>(null);
 useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(db));try{const bc=new BroadcastChannel('cm-v12');bc.postMessage(db);bc.close()}catch{}},[db]);
 useEffect(()=>{try{const bc=new BroadcastChannel('cm-v12');bc.onmessage=e=>e.data?.meds&&setDb(e.data);return()=>bc.close()}catch{}},[]);
 const schedule=useMemo(()=>db.meds.filter(m=>m.active&&m.start).map(m=>{const last=[...db.events].filter(e=>e.medId===m.id).sort((a,b)=>+new Date(b.confirmed)-+new Date(a.confirmed))[0];const base=last?.confirmed||m.start!;return {m,due:new Date(+new Date(base)+m.interval*60000)}}).sort((a,b)=>+a.due-+b.due),[db]);
 const pending=schedule.filter(x=>+x.due<=now&&(snoozes[x.m.id]||0)<=now).sort((a,b)=>+a.due-+b.due)[0];
 const upcoming=schedule.filter(x=>+x.due>now).sort((a,b)=>+a.due-+b.due); const next=upcoming[0];
 useEffect(()=>{if(pending&&!alarm&&!done){setAlarm(pending.m);startSound()}},[pending?.m.id,pending?.due]);
 function startSound(){try{const C=window.AudioContext||((window as any).webkitAudioContext);if(!C)return;const c=new C();audio.current=c;const beep=()=>{const o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=880;g.gain.value=.22;o.connect(g);g.connect(c.destination);o.start();setTimeout(()=>o.stop(),550)};beep();timer.current=window.setInterval(beep,1100)}catch{}}
 function stopSound(){if(timer.current)clearInterval(timer.current);timer.current=null;audio.current?.close();audio.current=null}
 function save(x:DB){setDb({...x})}
 function confirmMed(m:Med){stopSound();const item=schedule.find(x=>x.m.id===m.id);if(!item)return;const e:Event={id:crypto.randomUUID(),medId:m.id,scheduled:item.due.toISOString(),confirmed:nowIso(),by:role==='patient'?'Paciente':'Acompanhante'};save({...db,events:[...db.events,e]});setAlarm(null);setDone({med:m,event:e,next:new Date(Date.now()+m.interval*60000).toISOString()})}
 function snooze(m:Med,min:number){stopSound();setSnoozes(s=>({...s,[m.id]:Date.now()+min*60000}));setAlarm(null)}
 function setFirstTime(m:Med){save({...db,meds:db.meds.map(z=>z.id===m.id?{...z,start:nowIso(),active:true}:z)})}
 function addMed(name:string,interval:number,form:string,dose:string){save({...db,meds:[...db.meds,{id:crypto.randomUUID(),name:name.trim(),interval,start:null,active:true,form,dose}]});setShowAdd(false)}
 function pause(m:Med){save({...db,meds:db.meds.map(z=>z.id===m.id?{...z,active:!z.active}:z)})}
 function askNotifications(){if('Notification' in window)Notification.requestPermission().then(p=>alert(p==='granted'?'Notificações ativadas.':'Permissão não concedida.'))}
 function copy(){navigator.clipboard?.writeText(db.shareCode);alert('Código copiado.')}
 const overdue=alarm?schedule.find(x=>x.m.id===alarm.id):null;
 return <div className="min-h-screen bg-[#f6f8fc] text-[#172033]">
  <header className="sticky top-0 z-30 border-b border-slate-100 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-xl items-center justify-between px-5 py-4"><div><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-50 text-blue-600 shadow-sm"><HeartPulse size={24}/></span><div><div className="text-[10px] font-bold tracking-[.26em] text-slate-400">CONTROLE DE</div><h1 className="text-[25px] font-semibold leading-none tracking-tight">Medicamentos</h1></div></div><div className="mt-2 flex items-center gap-1.5 text-sm text-slate-500"><UserRound size={15}/> {role==='patient'?'Paciente':'Acompanhando'}: {db.patientName}</div></div><div className="flex items-center gap-1"><button onClick={askNotifications} aria-label="Notificações" className="rounded-2xl p-3 text-slate-600 hover:bg-slate-50"><Bell size={22}/></button><button onClick={()=>setMenu(v=>!v)} className="rounded-2xl bg-blue-50 px-4 py-3 font-bold text-blue-600">Sair</button></div></div></header>
  <main className="mx-auto max-w-xl px-5 pb-28 pt-5">
   {tab==='home'&&<>
    {!alarm&&!done&&<section className="relative mb-7 overflow-hidden rounded-[28px] bg-gradient-to-br from-blue-600 to-blue-700 px-7 py-6 text-white shadow-xl shadow-blue-100"><div className="absolute -right-12 -bottom-16 h-48 w-48 rounded-full border-[28px] border-white/5"/><div className="relative"><div className="flex items-center gap-2 text-sm font-bold uppercase tracking-wider text-white/75"><Clock3 size={18}/> Próxima medicação</div>{next?<><div className="mt-3 text-[22px] font-semibold leading-tight">{next.m.name}</div><div className="mt-1 text-[60px] font-black leading-none tracking-tight">{fmt(next.due.toISOString())}</div><div className="mt-3 text-lg font-bold">Em {duration(next.due.getTime()-now)}</div><p className="mt-1 text-sm text-white/75">Você será alertado quando chegar a hora.</p></>:<><div className="mt-4 text-2xl font-bold">Nenhum horário definido</div><p className="mt-2 text-white/75">Defina o primeiro horário de cada medicamento.</p></>}</div></section>}
    {done&&<section className="mb-7 rounded-[28px] border border-emerald-100 bg-emerald-50 p-6 shadow-sm"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-full bg-emerald-500 text-white shadow-lg"><Check size={30}/></div><div><div className="text-xl font-black text-emerald-700">Medicamento confirmado!</div><div className="text-sm text-emerald-700/70">Confirmado às {fmt(done.event.confirmed)}</div></div></div><div className="mt-5 rounded-2xl bg-white p-4"><div className="font-bold">{done.med.name}</div><div className="mt-1 text-sm text-slate-500">Próximo horário</div><div className="mt-1 text-2xl font-black text-emerald-600">{fmt(done.next)}</div><div className="text-xs text-slate-400">{dateFmt(done.next)}</div></div><button onClick={()=>setDone(null)} className="mt-4 w-full rounded-2xl bg-emerald-600 py-3 font-bold text-white">CONTINUAR</button></section>}
    <div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 text-[22px] font-bold"><CalendarDays size={22} className="text-slate-500"/> Próximos horários</h2></div>
    <div className="space-y-3">{upcoming.slice(0,7).map(x=><div key={x.m.id} className="group flex items-center gap-4 rounded-[24px] border border-slate-100 border-l-4 border-l-blue-600 bg-white p-4 shadow-[0_4px_18px_rgba(20,35,60,.04)]"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Clock3 size={23}/></div><div className="min-w-0 flex-1"><div className="truncate text-[16px] font-bold">{x.m.name}</div><div className="mt-1 text-sm text-slate-500">{fmt(x.due.toISOString())} <span className="text-slate-300">•</span> Em {duration(x.due.getTime()-now)}</div></div><ChevronRight size={21} className="text-slate-300"/></div>)}{pending&&<div className="rounded-[24px] border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700"><ShieldAlert size={18} className="mr-2 inline"/> Existe uma dose pendente. Confirme-a para liberar o próximo horário.</div>}{!upcoming.length&&!pending&&<div className="rounded-[24px] border border-dashed border-slate-300 bg-white p-8 text-center text-slate-500">Nenhum próximo horário. Defina o primeiro horário dos medicamentos.</div>}</div>
    <section className="mt-6 rounded-[26px] border border-blue-100 bg-gradient-to-br from-blue-50 to-white p-5"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-100 text-blue-600"><UsersRound size={24}/></div><div><div className="font-bold">Acompanhamento familiar</div><div className="text-sm text-slate-500">Compartilhe este código com quem acompanha você.</div></div></div><div className="mt-4 flex items-center justify-between rounded-2xl bg-white p-3 shadow-sm"><strong className="text-xl tracking-[.14em] text-blue-600">{db.shareCode}</strong><button onClick={copy} className="rounded-xl bg-blue-50 p-3 text-blue-600"><Copy size={19}/></button></div></section>
   </>}
   {tab==='meds'&&<><div className="mb-5 flex items-center justify-between"><div><h2 className="text-2xl font-bold">Medicamentos</h2><p className="text-sm text-slate-500">Controle simples do seu tratamento.</p></div><button onClick={()=>setShowAdd(true)} className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-100"><Plus size={24}/></button></div><div className="mb-4 flex gap-2 overflow-x-auto"><span className="shrink-0 rounded-full bg-blue-600 px-4 py-2 text-sm font-bold text-white">Todos</span><span className="shrink-0 rounded-full bg-white px-4 py-2 text-sm font-semibold text-slate-500">Em uso</span><span className="shrink-0 rounded-full bg-white px-4 py-2 text-sm font-semibold text-slate-500">Finalizados</span></div><div className="space-y-3">{db.meds.map(m=><div key={m.id} className="rounded-[24px] border border-slate-100 bg-white p-5 shadow-[0_4px_18px_rgba(20,35,60,.04)]"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-blue-50 text-xl">{m.form==='Colírio'?'💧':'💊'}</div><div className="min-w-0 flex-1"><h3 className="font-bold">{m.name}</h3><p className="mt-1 text-sm text-slate-500">{m.dose||'1 dose'} • A cada {m.interval>=1440?`${m.interval/1440} dias`:m.interval>=60?`${m.interval/60} horas`:`${m.interval} min`}</p><p className="text-xs text-slate-400">{m.form||'Medicamento'} • {m.active?'Em uso':'Pausado'}</p></div><button onClick={()=>pause(m)} className={`rounded-xl p-2 ${m.active?'bg-emerald-50 text-emerald-600':'bg-amber-50 text-amber-600'}`}>{m.active?<Pause size={18}/>:<Play size={18}/>}</button></div>{!m.start?<button onClick={()=>setFirstTime(m)} className="mt-4 w-full rounded-2xl bg-blue-600 py-3 font-bold text-white">Definir horário — já usei agora</button>:<div className="mt-4 rounded-2xl bg-slate-50 p-3 text-sm"><span className="text-slate-500">Base do ciclo:</span> <b>{fmt(m.start)}</b><span className="ml-2 font-semibold text-emerald-600">● Ativo</span></div>}</div>)}</div></>}
   {tab==='history'&&<><div className="mb-5"><h2 className="text-2xl font-bold">Histórico</h2><p className="text-sm text-slate-500">Tudo que foi confirmado e por quem.</p></div><div className="space-y-3">{[...db.events].reverse().map(e=><div key={e.id} className="rounded-[24px] border border-slate-100 bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><Check size={21}/></div><div className="min-w-0 flex-1"><div className="font-bold">{db.meds.find(m=>m.id===e.medId)?.name||'Medicamento'}</div><div className="mt-1 text-sm text-slate-500">Previsto {fmt(e.scheduled)} • Confirmado {fmt(e.confirmed)}</div><div className="mt-1 text-xs font-bold text-slate-400">{e.by} • {dateFmt(e.confirmed)}</div></div></div></div>)}{!db.events.length&&<div className="rounded-[24px] bg-white p-8 text-center text-slate-500">Nenhuma dose confirmada ainda.</div>}</div></>}
   {tab==='settings'&&<><h2 className="mb-5 text-2xl font-bold">Configurações</h2><div className="space-y-3"><button onClick={askNotifications} className="flex w-full items-center gap-4 rounded-[24px] bg-white p-5 text-left shadow-sm"><Bell className="text-blue-600"/><div><b>Notificações</b><p className="text-sm text-slate-500">Permitir alertas do navegador</p></div></button><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='controle-medicamentos-v1.2-backup.json';a.click()}} className="flex w-full items-center gap-4 rounded-[24px] bg-white p-5 text-left shadow-sm"><Copy className="text-blue-600"/><div><b>Exportar backup</b><p className="text-sm text-slate-500">Salvar seus dados em JSON</p></div></button><div className="rounded-[24px] bg-amber-50 p-5 text-sm text-amber-900"><b>Atenção:</b> o aplicativo é um organizador de horários. Não substitui orientação profissional.</div></div></>}
  </main>
  <nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-slate-200 bg-white/95 px-2 pb-[env(safe-area-inset-bottom)] backdrop-blur"><div className="mx-auto grid max-w-xl grid-cols-4 gap-1 py-2"><Nav active={tab==='home'} onClick={()=>setTab('home')} icon={<Home/>} label="Início"/><Nav active={tab==='meds'} onClick={()=>setTab('meds')} icon={<span className="text-xl">💊</span>} label="Medicamentos"/><Nav active={tab==='history'} onClick={()=>setTab('history')} icon={<History/>} label="Histórico"/><Nav active={tab==='settings'} onClick={()=>setTab('settings')} icon={<Settings/>} label="Configurações"/></div></nav>
  {alarm&&overdue&&<div className="fixed inset-0 z-50 flex min-h-screen items-center justify-center bg-[#df182b] p-5 text-white"><div className="w-full max-w-xl text-center"><button onClick={()=>snooze(alarm,5)} className="absolute right-5 top-5 grid h-12 w-12 place-items-center rounded-full bg-white/10"><X/></button><div className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-white/15 ring-8 ring-white/5"><ShieldAlert size={54}/></div><div className="mt-8 text-sm font-bold uppercase tracking-[.18em] text-white/80">Hora do medicamento!</div><span className="mt-4 inline-block rounded-full bg-white px-5 py-2 font-bold text-red-600">{+overdue.due<=now?'Dose atrasada':'Dose pendente'}</span><h2 className="mx-auto mt-5 max-w-lg text-3xl font-black leading-tight">{alarm.name}</h2><div className="mx-auto mt-7 max-w-sm rounded-[28px] bg-black/15 p-5"><div className="text-sm text-white/80">Deveria ter sido às</div><div className="mt-1 text-4xl font-black">{fmt(overdue.due.toISOString())}</div><div className="my-4 h-px bg-white/15"/><div className="text-sm text-white/80">{+overdue.due<=now?'Atrasado há':'Começa em'}</div><div className="text-2xl font-black">{duration(now-overdue.due.getTime())}</div></div><button onClick={()=>confirmMed(alarm)} className="mx-auto mt-6 flex w-full max-w-sm items-center justify-center gap-2 rounded-2xl bg-white px-5 py-4 text-base font-black text-red-600 shadow-xl"><Check size={21}/> CONFIRMAR {role==='patient'?'QUE FOI USADO':'QUE FOI ADMINISTRADO'}</button><div className="mx-auto mt-3 grid max-w-sm grid-cols-2 gap-3"><button onClick={()=>snooze(alarm,5)} className="rounded-2xl border border-white/60 px-3 py-3 font-bold">ADIAR 5 MIN</button><button onClick={()=>snooze(alarm,10)} className="rounded-2xl border border-white/60 px-3 py-3 font-bold">ADIAR 10 MIN</button></div><div className="mt-6 flex items-center justify-center gap-2 text-sm text-white/75"><Volume2 size={16}/> Alarme ativo enquanto o app estiver aberto</div></div></div>}
  {showAdd&&<AddModal onClose={()=>setShowAdd(false)} onSave={addMed}/>} 
  {menu&&<div className="fixed inset-0 z-40 bg-black/20" onClick={()=>setMenu(false)}><div className="absolute right-4 top-20 w-72 rounded-3xl bg-white p-3 shadow-2xl" onClick={e=>e.stopPropagation()}><button onClick={()=>{setRole('patient');localStorage.setItem('cm-role','patient');setMenu(false)}} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><UserRound/> Usar como paciente</button><button onClick={()=>{setRole('companion');localStorage.setItem('cm-role','companion');setMenu(false)}} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><UsersRound/> Acompanhar familiar</button><button onClick={()=>{localStorage.removeItem(KEY);location.reload()}} className="mt-1 flex w-full items-center gap-3 rounded-2xl p-3 text-left text-red-600 hover:bg-red-50"><LogOut/> Restaurar demonstração</button></div></div>}
 </div>}
function Nav({active,onClick,icon,label}:{active:boolean;onClick:()=>void;icon:React.ReactNode;label:string}){return <button onClick={onClick} className={`flex flex-col items-center gap-1 rounded-2xl px-2 py-2 text-[11px] font-bold ${active?'bg-blue-50 text-blue-600':'text-slate-500'}`}>{icon}<span>{label}</span></button>}
function AddModal({onClose,onSave}:{onClose:()=>void;onSave:(name:string,interval:number,form:string,dose:string)=>void}){const [name,setName]=useState('');const [form,setForm]=useState('Comprimido');const [dose,setDose]=useState('1 unidade');const [interval,setIntervalValue]=useState('12');const [unit,setUnit]=useState('horas');const submit=()=>{const n=Number(interval),mins=unit==='dias'?n*1440:unit==='horas'?n*60:n;if(!name.trim()||!Number.isFinite(mins)||mins<=0)return alert('Preencha o nome e um intervalo válido.');onSave(name,mins,form,dose)};return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/35 p-3 sm:items-center"><div className="w-full max-w-xl rounded-[30px] bg-white p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-widest text-slate-400">Novo tratamento</div><h2 className="text-xl font-bold">Adicionar medicamento</h2></div><button onClick={onClose} className="rounded-xl p-2 text-slate-500"><X/></button></div><label className="text-xs font-bold text-slate-500">Nome do medicamento<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Losartana 50mg" className="mt-1 w-full rounded-2xl border border-slate-200 p-3 outline-none focus:border-blue-500"/></label><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs font-bold text-slate-500">Apresentação<select value={form} onChange={e=>setForm(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3"><option>Comprimido</option><option>Cápsula</option><option>Gotas</option><option>Colírio</option><option>Pomada</option><option>Xarope</option><option>Outro</option></select></label><label className="text-xs font-bold text-slate-500">Dose<input value={dose} onChange={e=>setDose(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3"/></label></div><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs font-bold text-slate-500">A cada<input type="number" min="1" value={interval} onChange={e=>setIntervalValue(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3"/></label><label className="text-xs font-bold text-slate-500">Unidade<select value={unit} onChange={e=>setUnit(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3"><option>minutos</option><option>horas</option><option>dias</option></select></label></div><button onClick={submit} className="mt-5 w-full rounded-2xl bg-blue-600 py-4 font-bold text-white shadow-lg shadow-blue-100">Próximo</button></div></div>}
export default App;
