import { useRef, useState } from 'react';
import { Check, Clock3, Pencil, Pause, Pill, Play, ShieldAlert, Trash2, X } from 'lucide-react';
import type { Event, Med } from './model';
import { dueFor, duration, fmt } from './model';

type MedForm = { name: string; interval: number; unit: 'min' | 'hour' | 'day'; form: string; dose: string; note: string; photo: string | null };

export function NavButton({ active, icon, label, onClick }: { active: boolean; icon: React.ReactNode; label: string; onClick: () => void }) {
  return <button onClick={onClick} className={`flex min-h-16 flex-col items-center justify-center gap-1 rounded-2xl py-2.5 text-[11px] font-bold transition active:scale-[.98] ${active ? 'bg-blue-50 text-blue-600' : 'text-slate-500'}`}>{icon}<span>{label}</span></button>;
}

export function AlarmOverlay({ med, due, now, label, onConfirm, onSnooze }: { med: Med; due: Date; now: number; label: string; onConfirm: () => void; onSnooze: (m: number) => void }) {
  const late = Math.max(0, now - due.getTime());
  return <div className="fixed inset-0 z-[60] flex items-end justify-center bg-red-950/55 p-3 sm:items-center" role="alertdialog" aria-modal="true" aria-label={`Hora do medicamento ${med.name}`}>
    <div className="w-full max-w-md rounded-[32px] bg-gradient-to-br from-red-600 to-red-500 p-6 text-white shadow-2xl ring-1 ring-white/10">
      <div className="flex justify-center"><div className="grid h-20 w-20 place-items-center rounded-full bg-white/15 ring-8 ring-white/5"><ShieldAlert size={47}/></div></div>
      <div className="mt-5 text-center text-xs font-extrabold tracking-[.18em]">HORA DO MEDICAMENTO!</div>
      {late > 0 && <div className="mx-auto mt-3 w-fit rounded-full bg-white px-4 py-2 text-sm font-black text-red-600">DOSE ATRASADA</div>}
      <h2 className="mt-3 text-center text-3xl font-black leading-tight">{med.name}</h2>
      <div className="mt-5 rounded-2xl bg-red-800/35 p-4 text-center"><span className="text-sm opacity-90">Deveria ter sido às</span><strong className="mt-1 block text-3xl">{fmt(due)}</strong>{late > 0 ? <><span className="mt-3 block text-sm opacity-90">Atrasado há</span><strong className="block text-2xl">{duration(late)}</strong></> : <span className="mt-3 block text-sm opacity-90">É hora da dose.</span>}</div>
      <button onClick={onConfirm} autoFocus className="mt-4 flex w-full items-center justify-center gap-2 rounded-2xl bg-white py-4 font-black text-red-600 shadow-xl transition active:scale-[.98]"><Check size={22}/> CONFIRMAR QUE FOI {label}</button>
      <div className="mt-3 grid grid-cols-2 gap-3"><button onClick={() => onSnooze(5)} className="rounded-2xl border border-white/60 py-3 font-bold transition active:bg-white/10">ADIAR 5 MIN</button><button onClick={() => onSnooze(10)} className="rounded-2xl border border-white/60 py-3 font-bold transition active:bg-white/10">ADIAR 10 MIN</button></div>
      <p className="mt-4 text-center text-xs text-white/75">A dose permanece pendente até ser confirmada.</p>
    </div>
  </div>;
}

export function ConfirmationOverlay({ done, onClose, onNext }: { done: { med: Med; event: Event; next: Date }; onClose: () => void; onNext: () => void }) {
  return <div className="fixed inset-0 z-[65] flex items-end justify-center bg-emerald-950/25 p-3 sm:items-center"><div className="w-full max-w-md rounded-[32px] bg-white p-6 shadow-2xl">
    <div className="flex justify-end"><button onClick={onClose} className="rounded-full bg-slate-100 p-2" aria-label="Fechar"><X size={20}/></button></div>
    <div className="flex flex-col items-center text-center"><div className="grid h-20 w-20 place-items-center rounded-full bg-emerald-500 text-white shadow-lg"><Check size={48}/></div><div className="mt-5 text-2xl font-black text-emerald-700">Medicamento confirmado!</div><p className="mt-1 text-slate-500">Registro salvo com sucesso.</p>
      <div className="mt-5 w-full rounded-2xl bg-slate-50 p-4 text-left"><b className="text-lg">{done.med.name}</b><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><span className="block text-slate-400">Previsto</span><strong className="text-red-600">{fmt(done.event.scheduled)}</strong></div><div><span className="block text-slate-400">Confirmado</span><strong className="text-emerald-600">{fmt(done.event.confirmed)}</strong></div></div></div>
      <div className="mt-4 w-full rounded-2xl bg-emerald-50 p-4 text-left"><span className="text-sm text-emerald-700">Próximo horário</span><b className="mt-1 block text-lg">{done.med.name}</b><strong className="mt-1 block text-2xl text-emerald-700">{fmt(done.next)}</strong></div>
      <button onClick={onNext} className="mt-5 w-full rounded-2xl bg-emerald-600 py-3.5 font-black text-white transition active:scale-[.99]">CONTINUAR</button>
    </div></div></div>;
}

export function DetailSheet({ med, events, now, onClose, onConfirm, onPause, onEdit, onDelete }: { med: Med; events: Event[]; now: number; onClose: () => void; onConfirm: () => void; onPause: () => void; onEdit: () => void; onDelete: () => void }) {
  const due = dueFor(med, events); const last = [...events].filter(e => e.medId === med.id).sort((a, b) => +new Date(b.confirmed) - +new Date(a.confirmed))[0]; const overdue = !!due && +due <= now;
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/35 p-3 sm:items-center"><div className="max-h-[88vh] w-full max-w-md overflow-auto rounded-[30px] bg-white p-6 shadow-2xl">
    <div className="flex items-center justify-between"><div className="text-[10px] font-extrabold tracking-[.22em] text-slate-400">DETALHES DO MEDICAMENTO</div><button onClick={onClose} className="rounded-full bg-slate-100 p-2" aria-label="Fechar"><X size={19}/></button></div>
    <div className="mt-5 flex items-center gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-blue-50 text-blue-600">{med.photo ? <img src={med.photo} alt="" className="h-full w-full object-cover"/> : <Pill size={31}/>}</div><div className="min-w-0"><h2 className="text-2xl font-bold leading-tight">{med.name}</h2><p className="mt-1 text-sm text-slate-500">{med.form || 'Medicamento'} • {med.dose || '1 dose'}</p></div></div>
    <div className="mt-6 grid grid-cols-2 gap-3"><InfoBox label="Intervalo" value={med.interval >= 1440 ? `A cada ${med.interval / 1440} dias` : med.interval >= 60 ? `A cada ${med.interval / 60} horas` : `A cada ${med.interval} min`}/><InfoBox label="Situação" value={med.active ? 'Em uso' : 'Pausado'}/><InfoBox label="Próximo" value={due ? fmt(due) : 'Aguardando'}/><InfoBox label="Última confirmação" value={last ? fmt(last.confirmed) : 'Nenhuma'}/></div>
    {overdue && <div className="mt-4 rounded-2xl bg-red-50 p-4 text-sm font-bold text-red-700">🔴 Esta dose está atrasada e permanece pendente até ser confirmada.</div>}{med.note && <div className="mt-4 rounded-2xl bg-blue-50 p-4 text-sm text-blue-900"><b>Observação</b><p className="mt-1">{med.note}</p></div>}
    <div className="mt-5 grid grid-cols-2 gap-3"><button onClick={onPause} className="flex items-center justify-center gap-2 rounded-2xl border border-slate-200 py-3 font-bold">{med.active ? <Pause size={18}/> : <Play size={18}/>} {med.active ? 'Pausar' : 'Retomar'}</button><button onClick={onEdit} className="flex items-center justify-center gap-2 rounded-2xl bg-blue-600 py-3 font-bold text-white"><Pencil size={18}/> Editar</button></div>
    {overdue && <button onClick={onConfirm} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl bg-red-600 py-3.5 font-black text-white"><Check size={19}/> CONFIRMAR USO</button>}
    <button onClick={onDelete} className="mt-3 flex w-full items-center justify-center gap-2 rounded-2xl py-3 font-bold text-red-600"><Trash2 size={18}/> Excluir medicamento</button>
  </div></div>;
}
function InfoBox({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-slate-50 p-3"><span className="block text-xs text-slate-400">{label}</span><b className="mt-1 block text-sm">{value}</b></div>; }

function unitToMinutes(value: number, unit: MedForm['unit']) { return unit === 'day' ? value * 1440 : unit === 'hour' ? value * 60 : value; }
function minutesToForm(minutes: number): Pick<MedForm, 'interval' | 'unit'> { if (minutes % 1440 === 0) return { interval: minutes / 1440, unit: 'day' }; if (minutes % 60 === 0) return { interval: minutes / 60, unit: 'hour' }; return { interval: minutes, unit: 'min' }; }

export function StartTimeModal({ med, now, onClose, onSave }: { med: Med; now: number; onClose: () => void; onSave: (iso: string) => void }) {
  const current = new Date(now); const local = new Date(current.getTime() - current.getTimezoneOffset() * 60000).toISOString().slice(0, 16); const [value, setValue] = useState(local); const [error, setError] = useState('');
  function submit() { const selected = new Date(value); if (!value || Number.isNaN(selected.getTime())) return setError('Informe um horário válido.'); if (selected.getTime() > now + 30000) return setError('Esse horário não pode estar no futuro, pois ele representa uma dose que já foi tomada.'); onSave(selected.toISOString()); }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/35 p-3 sm:items-center"><div className="w-full max-w-md rounded-[30px] bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><div className="text-[10px] font-bold tracking-[.2em] text-slate-400">PRIMEIRO HORÁRIO</div><h2 className="text-2xl font-bold">{med.name}</h2></div><button onClick={onClose} className="rounded-full bg-slate-100 p-2"><X size={19}/></button></div><div className="mt-5 rounded-2xl bg-blue-50 p-4 text-sm text-blue-900">Defina o horário da dose que <b>já foi tomada</b>. O aplicativo usará esse horário como base para calcular a próxima dose.</div><label className="mt-5 block text-sm font-bold">Horário da dose tomada<input type="datetime-local" max={local} value={value} onChange={e => setValue(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3.5"/></label>{error && <div className="mt-3 rounded-2xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}<button onClick={submit} className="mt-5 w-full rounded-2xl bg-blue-600 py-4 font-black text-white">SALVAR E CALCULAR PRÓXIMO</button></div></div>;
}

export function AddModal({ onClose, onSave }: { onClose: () => void; onSave: (data: MedForm) => void }) {
  const [name, setName] = useState(''); const [interval, setIntervalValue] = useState(2); const [unit, setUnit] = useState<MedForm['unit']>('hour'); const [form, setForm] = useState('Colírio'); const [dose, setDose] = useState('1 gota'); const [note, setNote] = useState(''); const [photo, setPhoto] = useState<string | null>(null); const fileRef = useRef<HTMLInputElement>(null);
  function readPhoto(file?: File) { if (!file) return; if (file.size > 1024 * 1024) return alert('Escolha uma imagem de até 1 MB.'); const r = new FileReader(); r.onload = () => setPhoto(String(r.result)); r.readAsDataURL(file); }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/35 p-3 sm:items-center"><div className="max-h-[92vh] w-full max-w-md overflow-auto rounded-[30px] bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><div className="text-[10px] font-bold tracking-[.2em] text-slate-400">NOVO</div><h2 className="text-2xl font-bold">Adicionar medicamento</h2></div><button onClick={onClose} className="rounded-full bg-slate-100 p-2"><X size={19}/></button></div>
    <label className="mt-5 block text-sm font-bold">Nome<input value={name} onChange={e => setName(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3 outline-none focus:border-blue-500" placeholder="Nome do medicamento"/></label>
    <div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-bold">Intervalo<input type="number" min={1} value={interval} onChange={e => setIntervalValue(Math.max(1, Number(e.target.value) || 1))} className="mt-1 w-full rounded-2xl border border-slate-200 p-3"/></label><label className="text-sm font-bold">Unidade<select value={unit} onChange={e => setUnit(e.target.value as MedForm['unit'])} className="mt-1 w-full rounded-2xl border border-slate-200 p-3"><option value="min">Minutos</option><option value="hour">Horas</option><option value="day">Dias</option></select></label></div>
    <label className="mt-3 block text-sm font-bold">Forma<select value={form} onChange={e => setForm(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3">{['Colírio','Comprimido','Cápsula','Gotas','Pomada','Xarope','Injetável','Outro'].map(x => <option key={x}>{x}</option>)}</select></label>
    <label className="mt-3 block text-sm font-bold">Dose<input value={dose} onChange={e => setDose(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3" placeholder="1 gota / 1 comprimido"/></label>
    <label className="mt-3 block text-sm font-bold">Observação<textarea value={note} onChange={e => setNote(e.target.value)} className="mt-1 min-h-20 w-full rounded-2xl border border-slate-200 p-3" placeholder="Ex.: aplicar 7 min após outro medicamento"/></label>
    <div className="mt-3 flex items-center gap-3"><button type="button" onClick={() => fileRef.current?.click()} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold">{photo ? 'Trocar foto' : 'Adicionar foto'}</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={e => readPhoto(e.target.files?.[0])}/>{photo && <img src={photo} alt="Prévia" className="h-12 w-12 rounded-xl object-cover"/>}</div>
    <button disabled={!name.trim()} onClick={() => onSave({ name: name.trim(), interval: unitToMinutes(interval, unit), unit, form, dose, note, photo })} className="mt-5 w-full rounded-2xl bg-blue-600 py-3.5 font-black text-white disabled:opacity-40">Adicionar medicamento</button>
  </div></div>;
}

export function EditModal({ med, onClose, onSave }: { med: Med; onClose: () => void; onSave: (med: Med) => void }) {
  const initial = minutesToForm(med.interval); const [name, setName] = useState(med.name); const [interval, setIntervalValue] = useState(initial.interval); const [unit, setUnit] = useState<MedForm['unit']>(initial.unit); const [form, setForm] = useState(med.form || 'Colírio'); const [dose, setDose] = useState(med.dose || '1 dose'); const [note, setNote] = useState(med.note || ''); const [photo, setPhoto] = useState<string | null>(med.photo || null); const fileRef = useRef<HTMLInputElement>(null);
  function readPhoto(file?: File) { if (!file) return; if (file.size > 1024 * 1024) return alert('Escolha uma imagem de até 1 MB.'); const r = new FileReader(); r.onload = () => setPhoto(String(r.result)); r.readAsDataURL(file); }
  function save() { if (!name.trim()) return; onSave({ ...med, name: name.trim(), interval: unitToMinutes(Math.max(1, interval || 1), unit), form, dose: dose.trim(), note: note.trim(), photo }); }
  return <div className="fixed inset-0 z-[55] flex items-end justify-center bg-slate-950/35 p-3 sm:items-center"><div className="max-h-[92vh] w-full max-w-md overflow-auto rounded-[30px] bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><div className="text-[10px] font-bold tracking-[.2em] text-slate-400">EDITAR</div><h2 className="text-2xl font-bold">Medicamento</h2></div><button onClick={onClose} className="rounded-full bg-slate-100 p-2"><X size={19}/></button></div>
    <label className="mt-5 block text-sm font-bold">Nome<input value={name} onChange={e => setName(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3"/></label><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-bold">Intervalo<input type="number" min={1} value={interval} onChange={e => setIntervalValue(Number(e.target.value) || 1)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3"/></label><label className="text-sm font-bold">Unidade<select value={unit} onChange={e => setUnit(e.target.value as MedForm['unit'])} className="mt-1 w-full rounded-2xl border border-slate-200 p-3"><option value="min">Minutos</option><option value="hour">Horas</option><option value="day">Dias</option></select></label></div><label className="mt-3 block text-sm font-bold">Forma<select value={form} onChange={e => setForm(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3">{['Colírio','Comprimido','Cápsula','Gotas','Pomada','Xarope','Injetável','Outro'].map(x => <option key={x}>{x}</option>)}</select></label><label className="mt-3 block text-sm font-bold">Dose<input value={dose} onChange={e => setDose(e.target.value)} className="mt-1 w-full rounded-2xl border border-slate-200 p-3"/></label><label className="mt-3 block text-sm font-bold">Observação<textarea value={note} onChange={e => setNote(e.target.value)} className="mt-1 min-h-20 w-full rounded-2xl border border-slate-200 p-3"/></label><div className="mt-3 flex items-center gap-3"><button type="button" onClick={() => fileRef.current?.click()} className="rounded-2xl border border-slate-200 px-4 py-3 text-sm font-bold">{photo ? 'Trocar foto' : 'Adicionar foto'}</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={e => readPhoto(e.target.files?.[0])}/>{photo && <><img src={photo} alt="Prévia" className="h-12 w-12 rounded-xl object-cover"/><button type="button" onClick={() => setPhoto(null)} className="text-sm font-bold text-red-600">Remover</button></>}</div><button disabled={!name.trim()} onClick={save} className="mt-5 w-full rounded-2xl bg-blue-600 py-3.5 font-black text-white disabled:opacity-40">Salvar alterações</button>
  </div></div>;
}
