import { Bell, CalendarClock, Check, ChevronRight, Clock3, Copy, History, Pause, Pill, Play, Plus, ShieldAlert, UsersRound } from 'lucide-react';
import type { DB, Med } from './model';
import { dateFmt, duration, fmt } from './model';

export function HomeView({ db, activePending, next, upcoming, now, onDetail }: { db: DB; activePending: { med: Med; due: Date } | null; next: { m: Med; due: Date } | undefined; upcoming: { m: Med; due: Date }[]; now: number; onDetail: (m: Med) => void }) {
  const showNext = !activePending;
  return <>
    {activePending ? <section className="relative mb-7 overflow-hidden rounded-[28px] bg-gradient-to-br from-red-600 to-red-500 p-7 text-white shadow-[0_18px_45px_rgba(220,38,38,.22)]"><div className="absolute -bottom-20 -right-12 h-52 w-52 rounded-full border-[30px] border-white/10"/><div className="relative"><div className="mb-3 flex items-center justify-between gap-2"><span className="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1.5 text-xs font-extrabold tracking-wide"><ShieldAlert size={16}/> DOSE PENDENTE</span><span className="rounded-full bg-red-700/60 px-3 py-1.5 text-xs font-bold">ATRASADO</span></div><h2 className="text-[25px] font-bold leading-tight">{activePending.med.name}</h2><div className="mt-4 text-sm font-semibold opacity-90">Deveria ter sido às</div><div className="mt-1 flex items-center gap-2 text-[52px] font-black leading-none"><Clock3 size={35}/>{fmt(activePending.due)}</div><div className="mt-4 text-lg font-extrabold">🔴 Atrasado há {duration(now - activePending.due.getTime())}</div><p className="mt-1 text-sm font-medium opacity-90">Ainda não foi confirmado.</p><div className="mt-5 rounded-2xl bg-white/15 p-4 text-sm font-bold">Toque na tela de alerta para confirmar ou adiar a dose.</div></div></section> : showNext && <section className="relative mb-7 overflow-hidden rounded-[28px] bg-gradient-to-br from-blue-600 to-blue-700 p-7 text-white shadow-[0_18px_45px_rgba(37,99,235,.20)]"><div className="absolute -bottom-20 -right-12 h-52 w-52 rounded-full border-[30px] border-white/5"/><div className="relative"><div className="flex items-center gap-2 text-sm font-bold uppercase tracking-wide text-white/80"><CalendarClock size={19}/> Próximo medicamento</div>{next ? <><h2 className="mt-4 text-[25px] font-semibold leading-tight">{next.m.name}</h2><div className="mt-1 text-[60px] font-black leading-none tracking-tight">{fmt(next.due!)}</div><div className="mt-4 text-lg font-bold">Em {duration(next.due!.getTime() - now)}</div><p className="mt-1 text-sm text-white/75">Você será alertado quando chegar a hora.</p></> : <><div className="mt-4 text-2xl font-bold">Nenhum horário definido</div><p className="mt-2 text-white/75">Defina o primeiro horário de cada medicamento.</p></>}</div></section>}
    <div className="mb-4 flex items-center gap-2 text-[22px] font-bold"><Clock3 size={22} className="text-slate-500"/> {activePending ? 'Outros medicamentos' : 'Próximos horários'}</div>
    <div className="space-y-3">{upcoming.slice(0,8).map(x => <button key={x.m.id} onClick={() => onDetail(x.m)} className="group flex w-full items-center gap-4 rounded-[24px] border border-slate-100 border-l-4 border-l-blue-600 bg-white p-4 text-left shadow-[0_5px_20px_rgba(20,35,60,.045)] transition active:scale-[.99]"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Clock3 size={23}/></div><div className="min-w-0 flex-1"><div className="truncate text-[16px] font-bold">{x.m.name}</div><div className="mt-1 text-sm text-slate-500">{fmt(x.due)} <span className="text-slate-300">•</span> Em {duration(x.due.getTime() - now)}</div></div><ChevronRight size={22} className="shrink-0 text-slate-300"/></button>)}{activePending && upcoming.length === 0 && <div className="rounded-[24px] border border-dashed border-slate-300 bg-white p-7 text-center text-slate-500">Confirme a dose pendente para liberar o próximo horário.</div>}{!db.meds.some(m => m.start) && <div className="rounded-[24px] border border-dashed border-slate-300 bg-white p-8 text-center"><Clock3 size={30} className="mx-auto text-slate-400"/><b className="mt-3 block">Nenhum horário programado</b><span className="mt-1 block text-sm text-slate-500">Defina o primeiro horário dos seus medicamentos.</span></div>}</div>
    <section className="mt-6 rounded-[26px] border border-blue-100 bg-gradient-to-br from-blue-50 to-white p-5"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-100 text-blue-600"><UsersRound size={24}/></div><div><div className="font-bold">Acompanhamento familiar</div><div className="text-sm text-slate-500">Compartilhe este código com seus familiares.</div></div></div><div className="mt-4 flex items-center justify-between rounded-2xl bg-white p-3 shadow-sm"><strong className="text-xl tracking-[.14em] text-blue-600">{db.shareCode}</strong><button onClick={() => navigator.clipboard?.writeText(db.shareCode)} className="rounded-xl bg-blue-50 p-3 text-blue-600" aria-label="Copiar código"><Copy size={19}/></button></div></section>
  </>;
}

export function MedsView({ db, onAdd, onDetail, onPause, onStart }: { db: DB; onAdd: () => void; onDetail: (m: Med) => void; onPause: (m: Med) => void; onStart: (m: Med) => void }) { return <><div className="mb-5 flex items-center justify-between"><div><div className="text-[10px] font-bold tracking-[.22em] text-slate-400">SEUS MEDICAMENTOS</div><h2 className="text-2xl font-bold">Medicamentos</h2></div><button onClick={onAdd} className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-100"><Plus size={24}/></button></div><div className="space-y-3">{db.meds.map(m => <div key={m.id} className="rounded-[24px] border border-slate-100 bg-white p-5 shadow-sm"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-blue-50 text-blue-600">{m.form === 'Colírio' ? '💧' : '💊'}</div><div className="min-w-0 flex-1"><b className="block">{m.name}</b><span className="mt-1 block text-sm text-slate-500">{m.dose || '1 dose'} • A cada {m.interval >= 1440 ? `${m.interval / 1440} dias` : m.interval >= 60 ? `${m.interval / 60} horas` : `${m.interval} min`}</span><span className="mt-1 block text-xs text-slate-400">{m.form || 'Medicamento'} • {m.active ? 'Em uso' : 'Pausado'}</span></div><button onClick={() => onPause(m)} className={`rounded-xl p-2 ${m.active ? 'bg-emerald-50 text-emerald-600' : 'bg-amber-50 text-amber-600'}`}>{m.active ? <Pause size={18}/> : <Play size={18}/>}</button></div><div className="mt-4 flex gap-2"><button onClick={() => onDetail(m)} className="flex-1 rounded-2xl border border-slate-200 py-3 text-sm font-bold text-slate-700">Ver detalhes</button>{!m.start ? <button onClick={() => onStart(m)} className="flex-1 rounded-2xl bg-blue-600 py-3 text-sm font-bold text-white">Definir horário</button> : <button onClick={() => onStart(m)} className="flex-1 rounded-2xl bg-blue-50 py-3 text-sm font-bold text-blue-700">Alterar base</button>}</div></div>)}</div></>; }

export function HistoryView({ db }: { db: DB }) { return <><div className="mb-5"><div className="text-[10px] font-bold tracking-[.22em] text-slate-400">REGISTROS</div><h2 className="text-2xl font-bold">Histórico</h2><p className="text-sm text-slate-500">Veja o nome do medicamento, horário previsto e confirmação.</p></div><div className="space-y-3">{[...db.events].reverse().map(e => <div key={e.id} className="rounded-[24px] border border-slate-100 bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><Check size={21}/></div><div className="min-w-0 flex-1"><b className="block">{db.meds.find(m => m.id === e.medId)?.name || 'Medicamento'}</b><span className="mt-1 block text-sm text-slate-500">{e.by} • Previsto {fmt(e.scheduled)} • Confirmado {fmt(e.confirmed)}</span><small className="text-slate-400">{dateFmt(e.confirmed)}</small></div></div></div>)}{!db.events.length && <div className="rounded-[24px] border border-dashed border-slate-300 bg-white p-8 text-center text-slate-500">Nenhuma administração registrada ainda.</div>}</div></>; }

export function SettingsView({ db, onNotifications, onAlarm }: { db: DB; onNotifications: () => void; onAlarm: () => void }) { return <><div className="mb-5"><div className="text-[10px] font-bold tracking-[.22em] text-slate-400">APP</div><h2 className="text-2xl font-bold">Configurações</h2></div><div className="space-y-3"><button onClick={onNotifications} className="flex w-full items-center gap-3 rounded-2xl bg-white p-4 font-bold shadow-sm"><Bell size={20} className="text-blue-600"/> Ativar notificações</button><button onClick={onAlarm} className="flex w-full items-center gap-3 rounded-2xl bg-white p-4 font-bold shadow-sm"><span className="text-blue-600">🔔</span> Testar alarme</button><button onClick={() => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([JSON.stringify(db, null, 2)], { type: 'application/json' })); a.download = 'controle-medicamentos-v1.2-backup.json'; a.click(); }} className="flex w-full items-center gap-3 rounded-2xl bg-white p-4 font-bold shadow-sm"><History size={20} className="text-blue-600"/> Exportar backup</button><p className="rounded-2xl bg-blue-50 p-4 text-sm text-blue-900">A v1.2 mantém os dados no navegador e sincroniza abas abertas. Alarmes sonoros dependem da permissão de áudio do navegador.</p><p className="rounded-2xl bg-amber-50 p-4 text-sm text-amber-900">Este aplicativo organiza horários e registros. Não substitui orientação médica.</p></div></>; }
